require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ActionOneParametersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ActionOneParameter. As you add validations to ActionOneParameter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActionOneParametersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all action_one_parameters as @action_one_parameters" do
      action_one_parameter = ActionOneParameter.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:action_one_parameters)).to eq([action_one_parameter])
    end
  end

  describe "GET show" do
    it "assigns the requested action_one_parameter as @action_one_parameter" do
      action_one_parameter = ActionOneParameter.create! valid_attributes
      get :show, {:id => action_one_parameter.to_param}, valid_session
      expect(assigns(:action_one_parameter)).to eq(action_one_parameter)
    end
  end

  describe "GET new" do
    it "assigns a new action_one_parameter as @action_one_parameter" do
      get :new, {}, valid_session
      expect(assigns(:action_one_parameter)).to be_a_new(ActionOneParameter)
    end
  end

  describe "GET edit" do
    it "assigns the requested action_one_parameter as @action_one_parameter" do
      action_one_parameter = ActionOneParameter.create! valid_attributes
      get :edit, {:id => action_one_parameter.to_param}, valid_session
      expect(assigns(:action_one_parameter)).to eq(action_one_parameter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ActionOneParameter" do
        expect {
          post :create, {:action_one_parameter => valid_attributes}, valid_session
        }.to change(ActionOneParameter, :count).by(1)
      end

      it "assigns a newly created action_one_parameter as @action_one_parameter" do
        post :create, {:action_one_parameter => valid_attributes}, valid_session
        expect(assigns(:action_one_parameter)).to be_a(ActionOneParameter)
        expect(assigns(:action_one_parameter)).to be_persisted
      end

      it "redirects to the created action_one_parameter" do
        post :create, {:action_one_parameter => valid_attributes}, valid_session
        expect(response).to redirect_to(ActionOneParameter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved action_one_parameter as @action_one_parameter" do
        post :create, {:action_one_parameter => invalid_attributes}, valid_session
        expect(assigns(:action_one_parameter)).to be_a_new(ActionOneParameter)
      end

      it "re-renders the 'new' template" do
        post :create, {:action_one_parameter => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested action_one_parameter" do
        action_one_parameter = ActionOneParameter.create! valid_attributes
        put :update, {:id => action_one_parameter.to_param, :action_one_parameter => new_attributes}, valid_session
        action_one_parameter.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested action_one_parameter as @action_one_parameter" do
        action_one_parameter = ActionOneParameter.create! valid_attributes
        put :update, {:id => action_one_parameter.to_param, :action_one_parameter => valid_attributes}, valid_session
        expect(assigns(:action_one_parameter)).to eq(action_one_parameter)
      end

      it "redirects to the action_one_parameter" do
        action_one_parameter = ActionOneParameter.create! valid_attributes
        put :update, {:id => action_one_parameter.to_param, :action_one_parameter => valid_attributes}, valid_session
        expect(response).to redirect_to(action_one_parameter)
      end
    end

    describe "with invalid params" do
      it "assigns the action_one_parameter as @action_one_parameter" do
        action_one_parameter = ActionOneParameter.create! valid_attributes
        put :update, {:id => action_one_parameter.to_param, :action_one_parameter => invalid_attributes}, valid_session
        expect(assigns(:action_one_parameter)).to eq(action_one_parameter)
      end

      it "re-renders the 'edit' template" do
        action_one_parameter = ActionOneParameter.create! valid_attributes
        put :update, {:id => action_one_parameter.to_param, :action_one_parameter => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested action_one_parameter" do
      action_one_parameter = ActionOneParameter.create! valid_attributes
      expect {
        delete :destroy, {:id => action_one_parameter.to_param}, valid_session
      }.to change(ActionOneParameter, :count).by(-1)
    end

    it "redirects to the action_one_parameters list" do
      action_one_parameter = ActionOneParameter.create! valid_attributes
      delete :destroy, {:id => action_one_parameter.to_param}, valid_session
      expect(response).to redirect_to(action_one_parameters_url)
    end
  end

end
